---
title: "Wolrd_Visual"
output: word_document
---



```{r}
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)
library(ggplot2)
library(sf)
```

```{r}
world_data <- read_csv("trade-openness.csv") %>%
  filter(Year == 2019) 

world <- ne_countries(scale = "medium", returnclass = "sf")

world_data <- left_join(world, world_data, by = c("iso_a3" = "Code")) %>%
  filter(!admin == "Antarctica")



# Create trade openness ranges
world_data$trade_openness_range <- cut(world_data$`Trade openness (share of exports and imports in GDP)`,
                                       breaks = c(-Inf, 20, 40, 60, 80, Inf),
                                       labels = c("0-20%", "20-40%", "40-60%", "60-80%", "80-100%"))

# Plot map
plot_world_trade <- ggplot(world_data) +
  geom_sf(aes(fill = trade_openness_range)) +
  scale_fill_manual(values = c("#CCFF99", "#8EDD65", "#4FBF4F", "#219E4E", "#104D2D", "gray70"),
                    na.value = "gray70",
                    drop = FALSE,
                    labels = c("0 - 20%", "20 - 40%", "40 - 60%", "60 - 80%", "80 - 100%", "No Data")) +
  labs(title = "Trade Openness 2019",
       x = "Longitude",
       y = "Latitude",
       fill = "Trade openness (% of GDP)") +
  theme_void() +
  theme(plot.background = element_rect(fill = "#f2f2f2"),
        legend.position = "bottom",
        text = element_text(size = 12, family = "Times"),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 14, family = "Times"),
        plot.margin = unit(c(1,1,1,1), "cm")) +
  xlab("") + ylab("") +
  guides(fill = guide_legend(title = "Trade Openness (% of GDP)",
                              label.theme = element_text(size = 8),
                              override.aes = list(size = 5),
                              na.label = "No Data"))

ggsave("world_trade.pdf", plot = plot_world_trade)




```

